### ISSUE TITLE
Local 16B - Fin de Contrato de arrendamiento

### ISSUE THREAD

**Issue by jdpalermo** [GrupoPalermo/Bienes_Raices#34]
Cobros Pendientes
- [ ] Arrendamiento de Enero 2020
- [ ] Servicios Públicos Enero 2020
- [ ] Arrendamiento Febrero 2020
- [ ] Servicios Públicos Febrero 2020
